# Mosquitto Configuration - Development

listener 1883
protocol mqtt
allow_anonymous true
max_connections -1
max_queued_messages 1000
message_size_limit 0
retain_available true

listener 9001
protocol websockets
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true
